# Cloudflare Pages configuration with @cloudflare/next-on-pages

# Basic configuration
name = "openai-responses-app"
compatibility_date = "2025-05-10"

# This is what Cloudflare Pages is looking for
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility
node_compat = true

# Environment variables
[vars]
NEXT_TELEMETRY_DISABLED = "1"
