# Simple configuration for Cloudflare Pages

# Required: your project name
name = "openai-responses-starter-app"

# This is the path to deployment artifacts
pages_build_output_dir = ".vercel/output/static"

# Enable Node.js compatibility mode
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NEXT_TELEMETRY_DISABLED = "1"
